AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  toiletdb
  Sample SAM Template for toiletdb

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  CommonSrc:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: common_src/
      CompatibleRuntimes:
        - python3.9
    Metadata:
      BuildMethod: python3.9
  DBInterfaceFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: db_interface/
      Handler: app.lambda_handler
      Runtime: python3.9
      MemorySize: 128
      Timeout: 1000
      Policies: AmazonDynamoDBFullAccess
      Layers:
        - !Ref CommonSrc
        - !Sub arn:aws:lambda:ap-northeast-2:499644552089:layer:dynamodb-geo:3
        - !Sub arn:aws:lambda:ap-northeast-2:499644552089:layer:requests:4
        - !Sub arn:aws:lambda:ap-northeast-2:499644552089:layer:pandas:1
        - !Sub arn:aws:lambda:ap-northeast-2:499644552089:layer:xmltodict:2
      Environment:
        Variables:
          AWSENV : "AWS_SAM"
          DEVENV : "OSX"
          REGION : "ap-northeast-2" 
          TABLE : "build_info"
      Architectures:
        - x86_64
      Events:
        DBInterFace:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: POST
      
  
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  DBInterfaceAPI:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/interface"
  DBInterfaceFunction:
    Description: "DBInterface Function Arn"
    Value: !GetAtt DBInterfaceFunction.Arn
  # DBInterfaceFunctionIamRole:
  #   Description: "DBInterface IAM Arn"
  #   Value: !GetAtt DBInterfaceFunctionIAM.Arn
